Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/EndAlignment:
  AlignWith: start_of_line

Style/AndOr:
  EnforcedStyle: conditionals
