Style/ClassAndModuleChildren:
  EnforcedStyle: compact

Style/MethodDefParentheses:
  EnforcedStyle: require_no_parentheses

Style/StringLiterals:
  Enabled: false # more trouble than it's worth

Lint/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Style/AndOr:
  EnforcedStyle: conditionals
